- hosts: 10.4.7.22
  tasks:
    - name: Tarnsfer pem
      copy:
        src: "{{ item.source_file }}"
        dest: "{{ item.dest_file }}"
        mode: "{{ item.file_mode }}"
      with_items:
        - { source_file: 'template/kubelet-key.pem', dest_file: '/opt/kubernetes/server/bin/cert/', file_mode: '0600' }
        - { source_file: 'template/kubelet.pem', dest_file: '/opt/kubernetes/server/bin/cert/', file_mode: '0644' }

    - name: Create kubulet config
      script:
        cmd: template/kubelet_conf.sh
        chdir: /opt/kubernetes/server/bin/conf/
        creates: /opt/kubernetes/server/bin/conf/kubelet.kubeconfig
        executable: /usr/bin/bash
        #args:
          # creates 不能放在args下面, 不会生效的，同时executable也是一样的, 但是文档示例却是这么使用, 文档示例不是通过cmd执行的, 或许这就是区别了
          # creates: /opt/kubernetes/server/bin/conf/kubelet.kubeconfig

    - name: Tranfer k8s-node.yaml file
      copy:
        src: template/k8s-node.yaml
        dest: /opt/kubernetes/server/bin/conf/
        mode: '0644'

    - name: Set cluster role to etcd
      script:
        cmd: template/kubelet_cluster_role.sh
        chdir: /opt/kubernetes/server/bin/conf/
        executable: /usr/bin/bash
      ignore_errors: True

    - name: Create directory to kubelet start
      file:
        path: "{{ item.dir_path }}"
        state: directory
      with_items:
        - { dir_path: '/data/logs/kubernetes/kube-kubelet' }
        - { dir_path: '/data/kubelet' }

    - name: Split String to IP
      shell: echo "{{ ansible_default_ipv4.address }}" | awk -F '[.]+' '{print $3"-"$4}'
      register: network
      changed_when: false
        
    - name: Print Variables
      debug:
        msg: "{{ network }}"

    - name: Transfer kubelet.sh file and supervisor.ini
      template:
        src: "{{ item.source_file }}"
        dest: "{{ item.dest_file }}"
        mode: "{{ item.file_mode }}"
      with_items:
        - { source_file: 'template/kubelet.sh.j2', dest_file: '/opt/kubernetes/server/bin/kubelet.sh', file_mode: '0755' }
        - { source_file: 'template/kube-kubelet.ini.j2', dest_file: '/etc/supervisord.d/kube-kubelet.ini', file_mode: '0644' }
      notify: Exec supervisorctl update

  handlers:
    - name: Exec supervisorctl update
      shell: supervisorctl update
